### ISSUE TITLE
Backend Server

### ISSUE THREAD

**Issue by melitina915** [Friends-noonsong/Backend_Server#1]
## ✅ Checklist
- [x] 완료된 항목은 체크해주세요
- [x] 이슈 제목 작성

## ✏ Description
- Backend Server

## 📋 TODO
- [x] 뒤끝 서버 초기 설정
